export const brand = {
  name: "Mytool",
  tagline: {
    en: "Your AI work, made clearer.",
    ar: "اجعل عملك مع الذكاء الاصطناعي أكثر وضوحًا.",
  },
};

export const ui = {
  en: {
    assess: "Take the assessment",
    viewResults: "View my result",
    restart: "Start over",
    language: "العربية",
    home: "Overview",
    howItWorks: "How it works",
    assessment: "Assessment",
    heroKicker: "Practical AI fluency / 2026",
    heroTitle: "Make your AI judgment measurable.",
    heroBody: "Mytool turns everyday AI decisions into a clear, useful profile — so you know what to improve next, not just what you know today.",
    heroCardTitle: "A sharper AI practice",
    heroCardBody: "18 scenario-based questions. One honest read on how you work.",
    time: "8 min",
    duration: "Average time",
    categories: "6",
    categoriesLabel: "skill areas",
    questions: "18",
    questionsLabel: "real scenarios",
    private: "Private by design",
    privateBody: "No account. No data collection. Your result stays in this browser.",
    whatMeasures: "What Mytool looks at",
    measureBody: "The useful part of AI fluency is not memorizing features. It is knowing what to ask, what to trust, and what to do next.",
    startLine: "Ready when you are.",
    startBody: "Pick the answer that matches how you would actually work. There are no trick questions.",
    yourProgress: "Your progress",
    question: "Question",
    of: "of",
    back: "Back",
    next: "Next",
    finish: "See my result",
    chooseAnswer: "Choose the answer that best matches your approach.",
    answerRequired: "Choose an answer to continue.",
    resultKicker: "Your Mytool profile",
    resultTitle: "A clear read on your AI practice.",
    index: "Mytool index",
    outOf: "out of 100",
    strengths: "Strengths",
    growthAreas: "Growth areas",
    skillBreakdown: "Skill breakdown",
    yourProfile: "Your profile",
    recommendations: "Your next moves",
    recommendationsBody: "Small, focused habits will move your score faster than collecting more tools.",
    print: "Print / save PDF",
    printHint: "Use your browser’s print dialog and choose “Save as PDF”.",
    retake: "Retake assessment",
    levelFoundation: "Foundation",
    levelExplorer: "Explorer",
    levelPractitioner: "Practitioner",
    levelStrategist: "Strategist",
    levelFoundationBody: "You are building the fundamentals. A few repeatable habits will make AI feel much more dependable.",
    levelExplorerBody: "You have a useful base and are testing the edges. More structure will turn experiments into repeatable wins.",
    levelPractitionerBody: "You use AI with intention. Sharpening verification and tool choice will make your output even stronger.",
    levelStrategistBody: "You combine judgment, craft, and responsibility. You are ready to raise the quality of AI work around you.",
    strong: "Strong",
    developing: "Developing",
    focus: "Focus next",
    categoryQuestions: "questions",
    recommendationFallback: "Choose one recurring task this week and document a simple AI workflow for it.",
    recommendationsByCategory: {
      fundamentals: "Build a one-page AI glossary: model, context, prompt, hallucination, and output. Use it to explain your choices to someone else.",
      prompting: "Use a repeatable prompt frame: role, goal, context, constraints, and desired format. Save the best version as a template.",
      toolChoice: "Before opening a tool, define the job: create, transform, search, calculate, or decide. Then choose the lightest tool that can do it well.",
      practice: "Turn one frequent task into a three-step workflow: prepare the input, collaborate with AI, then review the result against a checklist.",
      critical: "Treat confident answers as drafts. Ask for sources, test key claims, and compare against a trusted reference before acting.",
      responsibility: "Create a personal red-line list for sensitive data, confidential work, personal information, and high-stakes decisions.",
    },
    categories: {
      fundamentals: { label: "AI basics", ar: "أساسيات الذكاء الاصطناعي", description: "Core concepts and mental models" },
      prompting: { label: "Prompting", ar: "هندسة الأوامر", description: "Turning intent into useful direction" },
      toolChoice: { label: "Tool choice", ar: "اختيار الأداة", description: "Matching tools to the job" },
      practice: { label: "Practical use", ar: "الاستخدام العملي", description: "Making AI useful in real work" },
      critical: { label: "Critical thinking", ar: "التفكير النقدي", description: "Checking quality before trust" },
      responsibility: { label: "Responsible AI", ar: "الاستخدام المسؤول", description: "Privacy, bias, and boundaries" },
    },
    prompts: {
      strengths: "Your strongest signals",
      growth: "Worth strengthening",
      highSignal: "High signal",
      mediumSignal: "Good base",
      lowSignal: "Build this habit",
      score: "score",
    },
  },
  ar: {
    assess: "ابدأ التقييم",
    viewResults: "عرض النتيجة",
    restart: "ابدأ من جديد",
    language: "English",
    home: "نظرة عامة",
    howItWorks: "كيف يعمل",
    assessment: "التقييم",
    heroKicker: "كفاءة عملية في الذكاء الاصطناعي / ٢٠٢٦",
    heroTitle: "حوّل قدرتك على استخدام الذكاء الاصطناعي إلى نتيجة واضحة.",
    heroBody: "يحوّل Mytool قراراتك اليومية مع الذكاء الاصطناعي إلى ملف عملي واضح، لتعرف ما الذي تطوّره بعد ذلك، وليس فقط ما تعرفه اليوم.",
    heroCardTitle: "ممارسة أذكى للذكاء الاصطناعي",
    heroCardBody: "١٨ سؤالًا مبنيًا على مواقف واقعية. قراءة واحدة صادقة لطريقة عملك.",
    time: "٨ دقائق",
    duration: "المدة المتوقعة",
    categories: "٦",
    categoriesLabel: "محاور للمهارة",
    questions: "١٨",
    questionsLabel: "موقفًا واقعيًا",
    private: "خصوصيتك أولًا",
    privateBody: "لا تحتاج إلى حساب، ولا نجمع بياناتك. تبقى نتيجتك في هذا المتصفح.",
    whatMeasures: "ما الذي يقيسه Mytool؟",
    measureBody: "الجزء المهم من الكفاءة في الذكاء الاصطناعي ليس حفظ الخصائص، بل معرفة ما الذي تسأله، وما الذي تثق به، وما الخطوة التالية.",
    startLine: "جاهز عندما تكون مستعدًا.",
    startBody: "اختر الإجابة التي تعبّر عن طريقتك الفعلية في العمل. لا توجد أسئلة خادعة.",
    yourProgress: "تقدّمك",
    question: "السؤال",
    of: "من",
    back: "السابق",
    next: "التالي",
    finish: "اعرض نتيجتي",
    chooseAnswer: "اختر الإجابة الأقرب إلى طريقتك.",
    answerRequired: "اختر إجابة للمتابعة.",
    resultKicker: "ملف Mytool الخاص بك",
    resultTitle: "قراءة واضحة لطريقتك في استخدام الذكاء الاصطناعي.",
    index: "مؤشر Mytool",
    outOf: "من ١٠٠",
    strengths: "نقاط القوة",
    growthAreas: "مجالات التطوير",
    skillBreakdown: "تفصيل المهارات",
    yourProfile: "ملفك",
    recommendations: "خطواتك التالية",
    recommendationsBody: "العادات الصغيرة المركّزة سترفع نتيجتك أسرع من جمع المزيد من الأدوات.",
    print: "طباعة / حفظ PDF",
    printHint: "استخدم نافذة الطباعة في المتصفح واختر «حفظ بتنسيق PDF».",
    retake: "إعادة التقييم",
    levelFoundation: "الأساس",
    levelExplorer: "المستكشف",
    levelPractitioner: "الممارس",
    levelStrategist: "الاستراتيجي",
    levelFoundationBody: "أنت تبني الأساسيات. بعض العادات المتكررة ستجعل استخدام الذكاء الاصطناعي أكثر اعتمادية.",
    levelExplorerBody: "لديك قاعدة جيدة وتختبر الحدود. المزيد من التنظيم سيحوّل التجارب إلى نتائج قابلة للتكرار.",
    levelPractitionerBody: "تستخدم الذكاء الاصطناعي بوعي. صقل التحقق واختيار الأداة سيجعل مخرجاتك أقوى.",
    levelStrategistBody: "تجمع بين الحكم الجيد والمهارة والمسؤولية. أنت مستعد لرفع جودة استخدام الذكاء الاصطناعي من حولك.",
    strong: "قوي",
    developing: "قيد التطوير",
    focus: "ركّز عليه",
    categoryQuestions: "أسئلة",
    recommendationFallback: "اختر مهمة متكررة هذا الأسبوع، ووثّق لها سير عمل بسيطًا باستخدام الذكاء الاصطناعي.",
    recommendationsByCategory: {
      fundamentals: "أنشئ قاموسًا من صفحة واحدة لمفاهيم: النموذج، والسياق، والأمر، والهلوسة، والمخرج. استخدمه لشرح اختياراتك لشخص آخر.",
      prompting: "استخدم قالبًا ثابتًا للأمر: الدور، والهدف، والسياق، والقيود، والتنسيق المطلوب. احتفظ بأفضل نسخة كقالب جاهز.",
      toolChoice: "قبل فتح أي أداة، حدّد المهمة: إنشاء، أو تحويل، أو بحث، أو حساب، أو اتخاذ قرار. ثم اختر أبسط أداة تؤديها جيدًا.",
      practice: "حوّل مهمة متكررة إلى سير عمل من ثلاث خطوات: جهّز المدخلات، تعاون مع الذكاء الاصطناعي، ثم راجع النتيجة وفق قائمة تحقق.",
      critical: "اعتبر الإجابات الواثقة مسودات. اطلب المصادر، واختبر الادعاءات المهمة، وقارنها بمرجع موثوق قبل اتخاذ أي قرار.",
      responsibility: "أنشئ قائمة شخصية بالخطوط الحمراء للبيانات الحساسة، والعمل السري، والمعلومات الشخصية، والقرارات عالية المخاطر.",
    },
    categories: {
      fundamentals: { label: "أساسيات الذكاء الاصطناعي", ar: "أساسيات الذكاء الاصطناعي", description: "المفاهيم والنماذج الذهنية الأساسية" },
      prompting: { label: "هندسة الأوامر", ar: "هندسة الأوامر", description: "تحويل النية إلى توجيه مفيد" },
      toolChoice: { label: "اختيار الأداة", ar: "اختيار الأداة", description: "مطابقة الأداة مع المهمة" },
      practice: { label: "الاستخدام العملي", ar: "الاستخدام العملي", description: "تحويل الذكاء الاصطناعي إلى قيمة فعلية" },
      critical: { label: "التفكير النقدي", ar: "التفكير النقدي", description: "فحص الجودة قبل الثقة" },
      responsibility: { label: "الاستخدام المسؤول", ar: "الاستخدام المسؤول", description: "الخصوصية والتحيز والحدود" },
    },
    prompts: {
      strengths: "أقوى الإشارات لديك",
      growth: "يستحق مزيدًا من التطوير",
      highSignal: "إشارة قوية",
      mediumSignal: "قاعدة جيدة",
      lowSignal: "ابنِ هذه العادة",
      score: "النتيجة",
    },
  },
};

export const questions = [
  {
    id: "fundamentals-1",
    category: "fundamentals",
    text: { en: "Which statement best describes generative AI?", ar: "أي عبارة تصف الذكاء الاصطناعي التوليدي بشكل أدق؟" },
    options: [
      { score: 4, en: "A system that learns patterns and creates new text, images, code, or audio from them.", ar: "نظام يتعلم الأنماط وينشئ نصوصًا أو صورًا أو برمجيات أو صوتًا جديدًا بناءً عليها." },
      { score: 2, en: "A search engine that always returns verified facts.", ar: "محرك بحث يعرض دائمًا حقائق تم التحقق منها." },
      { score: 1, en: "A database that stores every answer a person might need.", ar: "قاعدة بيانات تخزن كل إجابة قد يحتاجها الشخص." },
      { score: 1, en: "A human expert working behind a chat interface.", ar: "خبير بشري يعمل خلف واجهة محادثة." },
    ],
  },
  {
    id: "fundamentals-2",
    category: "fundamentals",
    text: { en: "What is an AI hallucination?", ar: "ما المقصود بـ «هلوسة» الذكاء الاصطناعي؟" },
    options: [
      { score: 4, en: "A plausible-sounding answer that contains made-up or unsupported information.", ar: "إجابة تبدو منطقية لكنها تتضمن معلومات مختلقة أو غير مدعومة." },
      { score: 1, en: "A visual effect in an AI-generated image.", ar: "تأثير بصري في صورة أنشأها الذكاء الاصطناعي." },
      { score: 2, en: "A brief delay while a model is generating an answer.", ar: "تأخير قصير أثناء إنشاء النموذج للإجابة." },
      { score: 1, en: "A model refusing to answer a difficult question.", ar: "رفض النموذج الإجابة عن سؤال صعب." },
    ],
  },
  {
    id: "fundamentals-3",
    category: "fundamentals",
    text: { en: "Why does the same prompt sometimes produce different answers?", ar: "لماذا قد ينتج الأمر نفسه إجابات مختلفة أحيانًا؟" },
    options: [
      { score: 4, en: "Models generate probable outputs, so context, settings, and randomness can change the result.", ar: "تنشئ النماذج مخرجات محتملة، لذلك قد يغيّر السياق والإعدادات والعشوائية النتيجة." },
      { score: 2, en: "The model only works correctly on its first attempt.", ar: "يعمل النموذج بشكل صحيح في المحاولة الأولى فقط." },
      { score: 1, en: "AI tools choose a different user at random.", ar: "تختار أدوات الذكاء الاصطناعي مستخدمًا مختلفًا عشوائيًا." },
      { score: 1, en: "The prompt is automatically translated each time.", ar: "تتم ترجمة الأمر تلقائيًا في كل مرة." },
    ],
  },
  {
    id: "prompting-1",
    category: "prompting",
    text: { en: "You need a useful first draft. Which prompt is the strongest starting point?", ar: "تحتاج إلى مسودة أولى مفيدة. أي أمر هو أفضل نقطة بداية؟" },
    options: [
      { score: 4, en: "Act as an editor. Rewrite these notes for a busy executive in 5 bullets, keep the numbers, and flag anything unclear.", ar: "تصرّف كمحرر. أعد صياغة هذه الملاحظات لمدير مشغول في ٥ نقاط، وحافظ على الأرقام، ونبّهني إلى أي شيء غير واضح." },
      { score: 2, en: "Make this better.", ar: "اجعل هذا أفضل." },
      { score: 2, en: "Write a professional version.", ar: "اكتب نسخة احترافية." },
      { score: 1, en: "Summarize.", ar: "لخّص." },
    ],
  },
  {
    id: "prompting-2",
    category: "prompting",
    text: { en: "When an answer misses the mark, what is the most useful next move?", ar: "عندما لا تصيب الإجابة الهدف، ما الخطوة التالية الأكثر فائدة؟" },
    options: [
      { score: 4, en: "Explain what was off, add the missing context, and specify the format or example you want.", ar: "اشرح ما الذي لم يكن مناسبًا، وأضف السياق الناقص، وحدد التنسيق أو المثال الذي تريده." },
      { score: 2, en: "Repeat the exact same prompt several times.", ar: "كرّر الأمر نفسه عدة مرات." },
      { score: 2, en: "Assume the tool cannot do the task.", ar: "افترض أن الأداة لا تستطيع تنفيذ المهمة." },
      { score: 1, en: "Add as many unrelated instructions as possible.", ar: "أضف أكبر عدد ممكن من التعليمات غير المرتبطة." },
    ],
  },
  {
    id: "prompting-3",
    category: "prompting",
    text: { en: "What makes an AI workflow easier to repeat?", ar: "ما الذي يجعل سير العمل باستخدام الذكاء الاصطناعي أسهل للتكرار؟" },
    options: [
      { score: 4, en: "A saved prompt template with clear inputs, constraints, an example, and a review step.", ar: "قالب أمر محفوظ يحدد المدخلات والقيود ومثالًا وخطوة للمراجعة." },
      { score: 2, en: "Using the longest prompt possible every time.", ar: "استخدام أطول أمر ممكن في كل مرة." },
      { score: 1, en: "Changing tools for every small task.", ar: "تغيير الأدوات في كل مهمة صغيرة." },
      { score: 1, en: "Leaving the result unedited so it stays authentic.", ar: "ترك النتيجة دون تعديل حتى تبقى أصلية." },
    ],
  },
  {
    id: "toolChoice-1",
    category: "toolChoice",
    text: { en: "You need to extract trends from a large spreadsheet. What is the best first choice?", ar: "تحتاج إلى استخراج اتجاهات من جدول بيانات كبير. ما الخيار الأفضل أولًا؟" },
    options: [
      { score: 4, en: "A spreadsheet or analysis tool, optionally paired with AI to explain the findings.", ar: "أداة جداول أو تحليل، ويمكن دعمها بالذكاء الاصطناعي لشرح النتائج." },
      { score: 2, en: "A general chat tool with the entire file pasted without structure.", ar: "أداة محادثة عامة مع لصق الملف كاملًا دون تنظيم." },
      { score: 2, en: "An image generator, because charts are visual.", ar: "أداة إنشاء الصور لأن الرسوم البيانية مرئية." },
      { score: 1, en: "A note-taking app with no calculation features.", ar: "تطبيق ملاحظات لا يحتوي على خصائص حسابية." },
    ],
  },
  {
    id: "toolChoice-2",
    category: "toolChoice",
    text: { en: "When is a specialized AI tool usually a better fit than a general chatbot?", ar: "متى تكون أداة ذكاء اصطناعي متخصصة أنسب عادة من روبوت محادثة عام؟" },
    options: [
      { score: 4, en: "When the task needs a specific workflow, data connection, or output format that tool is built for.", ar: "عندما تحتاج المهمة إلى سير عمل أو اتصال بالبيانات أو تنسيق مخرجات صُممت الأداة خصيصًا له." },
      { score: 2, en: "Whenever the tool has the newest logo.", ar: "عندما تحمل الأداة أحدث شعار." },
      { score: 1, en: "Only when the general chatbot is offline.", ar: "فقط عندما يكون روبوت المحادثة العام متوقفًا." },
      { score: 1, en: "Never; one tool should handle every task.", ar: "أبدًا؛ يجب أن تتولى أداة واحدة كل المهام." },
    ],
  },
  {
    id: "toolChoice-3",
    category: "toolChoice",
    text: { en: "What should guide your choice between two capable AI tools?", ar: "ما الذي يجب أن يوجه اختيارك بين أداتين قادرتين على أداء المهمة؟" },
    options: [
      { score: 4, en: "The task, quality bar, privacy needs, integration, and total effort — not hype alone.", ar: "المهمة، ومستوى الجودة المطلوب، واحتياجات الخصوصية، والتكامل، والجهد الكلي؛ وليس الضجة وحدها." },
      { score: 2, en: "Which one has the most features listed on its homepage.", ar: "الأداة التي تعرض أكبر عدد من الخصائص في صفحتها الرئيسية." },
      { score: 2, en: "Which one your colleague used once.", ar: "الأداة التي استخدمها زميلك مرة واحدة." },
      { score: 1, en: "Which one has the most complicated settings.", ar: "الأداة التي تملك الإعدادات الأكثر تعقيدًا." },
    ],
  },
  {
    id: "practice-1",
    category: "practice",
    text: { en: "What is a strong way to use AI for a recurring work task?", ar: "ما الطريقة القوية لاستخدام الذكاء الاصطناعي في مهمة عمل متكررة؟" },
    options: [
      { score: 4, en: "Define a repeatable workflow, give it the right context, and review the output against a checklist.", ar: "حدّد سير عمل قابلًا للتكرار، وقدّم السياق المناسب، وراجع المخرجات وفق قائمة تحقق." },
      { score: 2, en: "Ask AI to do everything without looking at the result.", ar: "اطلب من الذكاء الاصطناعي تنفيذ كل شيء دون مراجعة النتيجة." },
      { score: 2, en: "Use AI only for tasks that take less than one minute.", ar: "استخدم الذكاء الاصطناعي فقط للمهام التي تستغرق أقل من دقيقة." },
      { score: 1, en: "Start over from scratch every time to avoid bias.", ar: "ابدأ من الصفر في كل مرة لتجنب التحيز." },
    ],
  },
  {
    id: "practice-2",
    category: "practice",
    text: { en: "Which result shows AI is adding real value?", ar: "أي نتيجة تدل على أن الذكاء الاصطناعي يضيف قيمة حقيقية؟" },
    options: [
      { score: 4, en: "It reduces effort or improves quality while a person still owns the decision and final review.", ar: "يقلل الجهد أو يحسن الجودة مع بقاء القرار والمراجعة النهائية بيد الإنسان." },
      { score: 2, en: "It produces more words than the original task.", ar: "ينتج كلمات أكثر من المهمة الأصلية." },
      { score: 2, en: "It makes the process look more advanced.", ar: "يجعل العملية تبدو أكثر تطورًا." },
      { score: 1, en: "It removes every human checkpoint.", ar: "يلغي كل نقاط المراجعة البشرية." },
    ],
  },
  {
    id: "practice-3",
    category: "practice",
    text: { en: "You are using AI to prepare a presentation. What should you do before sharing it?", ar: "تستخدم الذكاء الاصطناعي لإعداد عرض تقديمي. ماذا تفعل قبل مشاركته؟" },
    options: [
      { score: 4, en: "Edit for audience and purpose, verify claims and numbers, then make the story your own.", ar: "عدّل المحتوى للجمهور والهدف، وتحقق من الادعاءات والأرقام، ثم اجعل القصة تعبّر عنك." },
      { score: 2, en: "Share it if the slides look polished.", ar: "شارك العرض إذا بدت الشرائح أنيقة." },
      { score: 2, en: "Add more slides to make it feel complete.", ar: "أضف شرائح أكثر ليبدو مكتملًا." },
      { score: 1, en: "Mention that AI made it and skip the review.", ar: "اذكر أن الذكاء الاصطناعي أنشأه وتجاوز المراجعة." },
    ],
  },
  {
    id: "critical-1",
    category: "critical",
    text: { en: "An AI gives you a precise statistic with no source. What do you do?", ar: "يعطيك الذكاء الاصطناعي إحصائية دقيقة دون مصدر. ماذا تفعل؟" },
    options: [
      { score: 4, en: "Ask for the source, verify it independently, and avoid using it if it cannot be supported.", ar: "اطلب المصدر، وتحقق منه بشكل مستقل، وتجنب استخدامه إذا تعذر دعمه." },
      { score: 2, en: "Use it because the number sounds realistic.", ar: "استخدمها لأن الرقم يبدو واقعيًا." },
      { score: 2, en: "Ask a second AI the same question and trust the majority.", ar: "اسأل أداة ذكاء اصطناعي ثانية السؤال نفسه وثق بالأغلبية." },
      { score: 1, en: "Round the number so it looks less suspicious.", ar: "قرّب الرقم حتى يبدو أقل إثارة للشك." },
    ],
  },
  {
    id: "critical-2",
    category: "critical",
    text: { en: "What is the best way to review an AI-generated recommendation?", ar: "ما أفضل طريقة لمراجعة توصية أنشأها الذكاء الاصطناعي؟" },
    options: [
      { score: 4, en: "Check assumptions, evidence, edge cases, and whether the recommendation fits the real context.", ar: "تحقق من الافتراضات والأدلة والحالات الاستثنائية ومدى ملاءمة التوصية للسياق الحقيقي." },
      { score: 2, en: "Choose it if the reasoning is long.", ar: "اخترها إذا كان التبرير طويلًا." },
      { score: 2, en: "Ask for a confident tone.", ar: "اطلب نبرة واثقة." },
      { score: 1, en: "Accept it when it matches your first instinct.", ar: "اقبلها عندما تتوافق مع انطباعك الأول." },
    ],
  },
  {
    id: "critical-3",
    category: "critical",
    text: { en: "Why is human review especially important for high-stakes decisions?", ar: "لماذا تعد المراجعة البشرية مهمة خصوصًا في القرارات عالية المخاطر؟" },
    options: [
      { score: 4, en: "AI can miss context, reproduce bias, or be confidently wrong; consequences need accountable judgment.", ar: "قد يفوّت الذكاء الاصطناعي السياق أو يكرر التحيز أو يخطئ بثقة؛ لذلك تحتاج العواقب إلى حكم مسؤول." },
      { score: 2, en: "AI is slower than people in every situation.", ar: "الذكاء الاصطناعي أبطأ من البشر في كل الحالات." },
      { score: 1, en: "Human review makes the result more expensive, which is the main reason.", ar: "المراجعة البشرية تجعل النتيجة أغلى، وهذا هو السبب الرئيسي." },
      { score: 1, en: "It is only needed when the interface looks unfinished.", ar: "تحتاج إليها فقط عندما تبدو الواجهة غير مكتملة." },
    ],
  },
  {
    id: "responsibility-1",
    category: "responsibility",
    text: { en: "Before pasting work into a public AI tool, what should you check?", ar: "قبل لصق محتوى العمل في أداة ذكاء اصطناعي عامة، ماذا يجب أن تتحقق منه؟" },
    options: [
      { score: 4, en: "Whether it contains confidential, personal, regulated, or proprietary information and whether the tool’s policy allows it.", ar: "ما إذا كان يتضمن معلومات سرية أو شخصية أو خاضعة للتنظيم أو مملوكة، وما إذا كانت سياسة الأداة تسمح بذلك." },
      { score: 2, en: "Whether the text is long enough to get a good answer.", ar: "ما إذا كان النص طويلًا بما يكفي للحصول على إجابة جيدة." },
      { score: 2, en: "Whether the tool has a colorful interface.", ar: "ما إذا كانت واجهة الأداة ملوّنة." },
      { score: 1, en: "Nothing; public tools are automatically safe.", ar: "لا شيء؛ الأدوات العامة آمنة تلقائيًا." },
    ],
  },
  {
    id: "responsibility-2",
    category: "responsibility",
    text: { en: "What is a responsible way to communicate AI-assisted work?", ar: "ما الطريقة المسؤولة للتواصل بشأن عمل ساعد الذكاء الاصطناعي في إنجازه؟" },
    options: [
      { score: 4, en: "Be transparent when it matters, take ownership of the final work, and check for errors or bias.", ar: "كن واضحًا عندما يكون ذلك مهمًا، وتحمل مسؤولية العمل النهائي، وتحقق من الأخطاء أو التحيز." },
      { score: 2, en: "Hide all AI assistance so people judge the result fairly.", ar: "أخفِ أي مساعدة من الذكاء الاصطناعي حتى يحكم الناس على النتيجة بعدل." },
      { score: 2, en: "Add an AI disclaimer to every sentence.", ar: "أضف تنويهًا عن الذكاء الاصطناعي إلى كل جملة." },
      { score: 1, en: "Let the tool take responsibility because it made the draft.", ar: "دع الأداة تتحمل المسؤولية لأنها أنشأت المسودة." },
    ],
  },
  {
    id: "responsibility-3",
    category: "responsibility",
    text: { en: "When is it safest to avoid sending personal data to an AI tool?", ar: "متى يكون تجنب إرسال البيانات الشخصية إلى أداة ذكاء اصطناعي هو الخيار الأكثر أمانًا؟" },
    options: [
      { score: 4, en: "When the task can be completed with anonymized, synthetic, or redacted information instead.", ar: "عندما يمكن تنفيذ المهمة باستخدام معلومات مجهّلة أو اصطناعية أو منقّحة بدلًا منها." },
      { score: 2, en: "Only when the data is written in a different language.", ar: "فقط عندما تكون البيانات مكتوبة بلغة مختلفة." },
      { score: 2, en: "When the tool’s answer might be too short.", ar: "عندما تكون إجابة الأداة قصيرة جدًا." },
      { score: 1, en: "Never; personal data improves every AI answer.", ar: "أبدًا؛ البيانات الشخصية تحسن كل إجابة من الذكاء الاصطناعي." },
    ],
  },
];

export const categoryOrder = ["fundamentals", "prompting", "toolChoice", "practice", "critical", "responsibility"];